name: trunk-io/plugins setup for trunk check/upgrade
description: Set up

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: find yamls
      run: find . | grep ".yaml"
      shell: bash

    - name: pwd
      run: pwd
      shell: bash

    - name: cp
      run: cp ${TRUNK_PATH} ./trunk.sh
      shell: bash

    - name: Config print
      run: ./trunk.sh config print
      shell: bash

    # - name: Config print
    #   uses: trunk-io/breakpoint@v1
    #   with:
    #     breakpoint-id: trunk-plugins-debug
    #     shell: bash
    #     working-directory: ${{ . }}
    #     trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
    #     org: trunk-staging-org
    #     run: ./trunk.sh config print
